### ISSUE TITLE
doesn't work with gnome 3.26 (alpha)

### ISSUE THREAD

**Issue by Cynede** [lagartoflojo/github-shell-extension#33]

**Comment by lagartoflojo** [comment]
Thanks for the report @mpkh, I will test it on Gnome 3.26 as soon as I get my hands on it.

**Comment by beanaroo** [comment]
I has been working on GNOME 3.26 and 3.26.1 for me on Arch Linux

**Comment by lagartoflojo** [comment]
@beanaroo Thanks for the confirmation!
