### ISSUE TITLE
make the updated repo distinguishable 

### ISSUE THREAD

**Issue by ItamarShDev** [lagartoflojo/github-shell-extension#34]
I have multiple repos.
when there is an update, the icon becomes red.
but when clicking on it, i cant seem to understand what was updated

**Comment by lagartoflojo** [comment]
Hi @ItamarShDev,
In GnomeHub, the only icon used so far is the one in the top panel, but that one never changes colors, so I'm not sure what you mean by "the icon becomes red"

**Comment by ItamarShDev** [comment]
Yes, my fault. i wrote this while fighting my way through my code, must have been confused

thanks!
