### ISSUE TITLE
Permissions needed

### ISSUE THREAD

**Issue by depado** [lagartoflojo/github-shell-extension#38]
Hey there
Great extension ! I love it so far. 
Could you explain what are the scopes required for the access token ? (And document it somewhere ?)
Also a button to test that the username/token actually work would be great 👍

**Comment by lagartoflojo** [comment]
Hi @Depado, thanks for the comments!
That's a very good idea, you are right that it's not defined anywhere. I will add it to the readme. For now...

If you want to work with **private** repos, you need to enable the `repo` scope:

![image](https://user-images.githubusercontent.com/2944/31390329-e8a41516-add3-11e7-81ee-80d408ab8ce6.png)

If you only need access to **public** repos, you can just select `public_repo`:

![image](https://user-images.githubusercontent.com/2944/31390426-24478b66-add4-11e7-8a09-25edb0ef7ae2.png)

**Comment by depado** [comment]
Nice ! Thanks a lot 🕺

**Comment by lagartoflojo** [comment]
I will leave this open so I remember to document it :)

**Comment by depado** [comment]
No problem 😉

**Comment by lagartoflojo** [comment]
Fixed in https://github.com/lagartoflojo/gnomehub/commit/8b863b141b9e879cb9aa50aeaeebabbc588ff8a7

**Comment by depado** [comment]
Thanks ! 🎉
