### ISSUE TITLE
Too many arguments error spamming the journal.

### ISSUE THREAD

**Issue by beanaroo** [lagartoflojo/github-shell-extension#39]
```
JS WARNING: [gnomehub@hschmidt.suse.com/pullRequestMenuItem.js 38]: Too many arguments to method Clutter.Actor.add_child: expected 1, got 2
```

This seems to be occurring every poll. Line 38 on the version I have installed is:
```
    this.actor.add_child(this._icon, { align: St.Align.END });
```

Removing the second argument seems to fix it, but I don't know enough JS to open a PR and I see the same thing being done [here](https://github.com/GNOME/gnome-shell/blob/c12da66da8b82f762c47109735391488ca2cfee9/js/ui/popupMenu.js#L398).

I am running GNOME 3.26.1 on Arch

**Comment by lagartoflojo** [comment]
Thanks for the heads-up. I'm downloading Arch to try it out there :)

**Comment by lagartoflojo** [comment]
Latest version of GnomeHub should get rid of this problem.
It will be out as soon as it's reviewed by someone in extensions.gnome.org :)
