### ISSUE TITLE
GnomeHub (10?) and GNOME 3.26 lead to GNOME instability

### ISSUE THREAD

**Issue by taw00** [lagartoflojo/github-shell-extension#45]
(a) GnomeHub simply didn't work at all for me. Plug in the info, including the auth token, and... nothing.
(b) Once installed, every few hours gnome-shell would crash.

I have no idea if either are related, but... disappointing.

**Comment by lagartoflojo** [comment]
Hi @taw00 thanks for the information, sorry to hear it's not working for you!

I'll be away from a computer the rest of this week, so I will have a look at this issue next week.

**Comment by depado** [comment]
@taw00 Can you open the debug console by doing <kbd>Alt</kbd>+<kbd>F2</kbd> and typing in `lg` ?
Then head to the `Extensions` tab, find GnomeHub in the list and click on `Display Errors`. That could help with the debugging.

**Comment by taw00** [comment]
Eek. It has been YEARS now since I looked at this issue. Alas, it does not work with my current version of GNOME. I am just going to close this.
