### ISSUE TITLE
Doesn't work with 2-step verification

### ISSUE THREAD

**Issue by benjamin21st** [lagartoflojo/github-shell-extension#46]
**What happened:**
My github account has 2-step verification, so entering the correct user name and password in Gnomehub wasn't sufficient to log me in and access status of my repos. Therefore I get the "Authorization Error" from Gnome dropdown.

**What is expected:**
A dialog/or other UI ways to inform me that 2-step verification is enabled and ask Github to send me a verification code, upon entering I could be using the cool extension.

**Comment by lagartoflojo** [comment]
Hi @benjamin21st, I also have 2FA enabled in my account, but it's not a problem.
You need to generate an access token to allow GnomeHub to access your repos. This is not the same as your GitHub password.
Open the GnomeHub settings panel and click on the "Create a new access token" link. Once you've created it, paste it into the "Access Token" field.

![image](https://user-images.githubusercontent.com/2944/39120545-0943e026-46ef-11e8-8406-bed8be429553.png)
